
export interface GxsdtBradescoApiRegistro {
    endEletronicoSacadorAvalista: string;
    nuCpfcnpjSacadorAvalista: string;
    cdIndCpfcnpjSacadorAvalista: string;
    ufSacadorAvalista: string;
    municipioSacadorAvalista: string;
    bairroSacadorAvalista: string;
    complementoCepSacadorAvalista: string;
    cepSacadorAvalista: string;
    complementoLogradouroSacadorAvalista: string;
    nuLogradouroSacadorAvalista: string;
    logradouroSacadorAvalista: string;
    nomeSacadorAvalista: string;
    endEletronicoPagador: string;
    nuCpfcnpjPagador: string;
    cdIndCpfcnpjPagador: string;
    ufPagador: string;
    municipioPagador: string;
    bairroPagador: string;
    complementoCepPagador: string;
    cepPagador: string;
    complementoLogradouroPagador: string;
    nuLogradouroPagador: string;
    logradouroPagador: string;
    nomePagador: string;
    vlIOF: string;
    vlAbatimento: string;
    dtLimiteBonificacao: string;
    vlBonificacao: string;
    percentualBonificacao: string;
    prazoBonificacao: string;
    dataLimiteDesconto3: string;
    vlDesconto3: string;
    percentualDesconto3: string;
    dataLimiteDesconto2: string;
    vlDesconto2: string;
    percentualDesconto2: string;
    dataLimiteDesconto1: string;
    vlDesconto1: string;
    percentualDesconto1: string;
    qtdeDiasMulta: string;
    vlMulta: string;
    percentualMulta: string;
    qtdeDiasJuros: string;
    vlJuros: string;
    percentualJuros: string;
    qtdePagamentoParcial: string;
    cdPagamentoParcial: string;
    controleParticipante: string;
    prazoProtestoAutomaticoNegativacao: string;
    tpProtestoAutomaticoNegativacao: string;
    cdEspecieTitulo: string;
    vlNominalTitulo: string;
    tpVencimento: string;
    dtVencimentoTitulo: string;
    dtEmissaoTitulo: string;
    nuCliente: string;
    nuTitulo: string;
    cdProduto: string;
    tpRegistro: string;
    eNuSequenciaContrato: string;
    cdBanco: string;
    nuNegociacao: string;
    idProduto: string;
    nuSequenciaContrato: string;
    cdTipoContrato: string;
    clubBanco: string;
    cdTipoAcesso: string;
    ctrlCPFCNPJ: string | null;
    filialCPFCNPJ: string | null;
    nuCPFCNPJ: string | null;
}
        
export interface GxsdtBradescoApiRegistroRetorno {
    cdErro: number | null;
    msgErro: string | null;
    idProduto: number;
    negociacao: number;
    clubBanco: number;
    tpContrato: number;
    nuSequenciaContrato: number;
    cdProduto: number;
    nuTituloGerado: number;
    agenciaCreditoBeneficiario: number;
    contaCreditoBeneficiario: number;
    digCreditoBeneficiario: string;
    cdCipTitulo: number;
    statusTitulo: number;
    descStatusTitulo: string;
    nomeBeneficiario: string;
    logradouroBeneficiario: string;
    nuLogradouroBeneficiario: string;
    complementoLogradouroBeneficiario: string;
    bairroBeneficiario: string;
    cepBeneficiario: number;
    cepComplementoBeneficiario: number;
    municipioBeneficiario: string;
    ufBeneficiario: string;
    razaoContaBeneficiario: number;
    nomePagador: string;
    cpfcnpjPagador: number;
    enderecoPagador: string;
    bairroPagador: string;
    municipioPagador: string;
    ufPagador: string;
    cepPagador: number;
    cepComplementoPagador: string;
    endEletronicoPagador: string;
    nomeSacadorAvalista: string;
    cpfcnpjSacadorAvalista: number;
    enderecoSacadorAvalista: string;
    municipioSacadorAvalista: string;
    ufSacadorAvalista: string;
    cepSacadorAvalista: number;
    cepComplementoSacadorAvalista: number;
    numeroTitulo: string;
    dtRegistro: string;
    especieDocumentoTitulo: string;
    descEspecie: string;
    vlIOF: number;
    dtEmissao: string;
    dtVencimento: string;
    vlTitulo: number;
    vlAbatimento: number;
    dtInstrucaoProtestoNegativacao: string;
    diasInstrucaoProtestoNegativacao: number;
    dtMulta: string;
    vlMulta: number;
    qtdeCasasDecimaisMulta: number;
    cdValorMulta: number;
    descCdMulta: string;
    dtJuros: string;
    vlJurosAoDia: number;
    dtDesconto1Bonificacao: number;
    vlDesconto1Bonificacao: number;
    qtdeCasasDecimaisDesconto1Bonificacao: number;
    cdValorDesconto1Bonificacao: number;
    descCdDesconto1Bonificacao: string;
    dtDesconto2: string;
    vlDesconto2: number;
    qtdeCasasDecimaisDesconto2: number;
    cdValorDesconto2: number;
    descCdDesconto2: string;
    dtDesconto3: string;
    vlDesconto3: number;
    qtdeCasasDecimaisDesconto3: number;
    cdValorDesconto3: number;
    descCdDesconto3: string;
    diasDispensaMulta: number;
    diasDispensaJuros: number;
    cdBarras: string;
    linhaDigitavel: string;
    cdAcessorioEscrituralEmpresa: number;
    tpVencimento: number;
    indInstrucaoProtesto: number;
    tipoAbatimentoTitulo: number;
    cdValorJuros: number;
    tpDesconto1: number;
    tpDesconto2: number;
    tpDesconto3: number;
    nuControleParticipante: string;
    diasJuros: number;
    cdJuros: number;
    vlJuros: number;
    cpfcnpjBeneficiario: string;
    vlTituloEmitidoBoleto: number;
    dtVencimentoBoleto: string;
    indTituloPertenceBaseTitulos: string;
    dtLimitePagamentoBoleto: string;
    cdIdentificacaoTituloDDACIP: number | null;
    indPagamentoParcial: string;
    qtdePagamentoParciais: number;
}
        
export interface GxsdtBradescoApiRetorno {
    id: number;
    mensagem: string;
}
        
export interface GxsdtBradescoApi {
    ListaDuplicata: number[];
    Acao: string;
    Registro: GxsdtBradescoApiRegistro;
    RegistroRetorno: GxsdtBradescoApiRegistroRetorno;
    Retorno: GxsdtBradescoApiRetorno[];
}
        