
export interface GxsdtBoletos {
    Bol_DataProcessamento: string;
    Bol_Carteira: string;
    Ced_Banco: string;
    Ced_Agencia: string;
    Ced_DigitoAgencia: string;
    Ced_NumeroConta: string;
    Ced_DigitoConta: string;
    Ced_Convenio: string;
    Ced_NomeCedente: string;
    Ced_Endereco: string;
    Ced_CodigoCedente: string;
    Ced_DigitoCodigoCedente: string;
    Ced_TipoPessoa: string;
    Ced_CnpjCpf: string;
    Sac_Nome: string;
    Sac_TipoPessoa: string;
    Sac_CnpjCpf: string;
    Sac_Rua: string;
    Sac_Cep: string;
    Sac_Cidade: string;
    Sac_Estado: string;
    Sac_Bairro: string;
    Cob_NossoNumero: string;
    Cob_ValorDocumento: string | null;
    Cob_DataDocumento: string;
    Cob_DataVencimento: string;
    Cob_NumeroDocumento: string;
    Cob_Instrucoes1: string;
    Cob_Instrucoes2: string;
    Cob_Instrucoes3: string;
    Cob_Instrucoes4: string;
    Cob_Instrucoes5: string;
    Cob_LocalPagamento: string;
    Cob_SeuNumero: string;
    TipoImpressaoDuplicata: string;
    Rem_LayoutArquivo: string;
    Rem_NumeroArquivo: number;
    ValorMoraJuros: string | null;
    DataProtesto: string;
    InstrucaoEspecial: string;
    Inst1: string;
    Inst2: string;
    Ced_TipoCobranca: string;
    Ced_CaracTitulo: number;
    Cob_CodigoGeracao: string;
    PercentualMulta: string | null;
    Parcela: string;
    TotalParcelas: string | null;
    NumDiasNegativacao: string;
    Ocorrencia: string;
    ValorAbatimento: string;
    DataAbatimento: string;
    DataBaixa: string;
    VersaoArquivo: string;
    VersaoLote: string;
    CodigoTransmissao: string;
}
        